### ISSUE TITLE
导入代码报了很多错误；能上传一下数据库脚本吗，文件导入失败

### ISSUE THREAD

**Issue by ghost** [ygsama/BooK-Library-System#2]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	CS0234	命名空间“Microsoft.VisualBasic”中不存在类型或命名空间名“PowerPacks”(是否缺少程序集引用?)	图书管理系统	D:\C#Project\BooK-Library-System-master\图书管理系统\BorrowBooks.Designer.cs	345	活动的
错误	CS0234	命名空间“Microsoft.VisualBasic”中不存在类型或命名空间名“PowerPacks”(是否缺少程序集引用?)	图书管理系统	D:\C#Project\BooK-Library-System-master\图书管理系统\BorrowBooks.Designer.cs	344	活动的
错误	CS0234	命名空间“Microsoft.VisualBasic”中不存在类型或命名空间名“PowerPacks”(是否缺少程序集引用?)	图书管理系统	D:\C#Project\BooK-Library-System-master\图书管理系统\ReturnBooks.Designer.cs	392	活动的
错误	CS0234	命名空间“Microsoft.VisualBasic”中不存在类型或命名空间名“PowerPacks”(是否缺少程序集引用?)	图书管理系统	D:\C#Project\BooK-Library-System-master\图书管理系统\ReturnBooks.Designer.cs	393	活动的
错误	CS0234	命名空间“Microsoft.VisualBasic”中不存在类型或命名空间名“PowerPacks”(是否缺少程序集引用?)	图书管理系统	D:\C#Project\BooK-Library-System-master\图书管理系统\BorrowBooks.Designer.cs	54	活动的
错误	CS0234	命名空间“Microsoft.VisualBasic”中不存在类型或命名空间名“PowerPacks”(是否缺少程序集引用?)	图书管理系统	D:\C#Project\BooK-Library-System-master\图书管理系统\BorrowBooks.Designer.cs	55	活动的
错误	CS0234	命名空间“Microsoft.VisualBasic”中不存在类型或命名空间名“PowerPacks”(是否缺少程序集引用?)	图书管理系统	D:\C#Project\BooK-Library-System-master\图书管理系统\BorrowBooks.Designer.cs	273	活动的
警告	CS0108	'“ReturnBooks.Tag”隐藏继承的成员“Control.Tag”。如果是有意隐藏，请使用关键字 new。	图书管理系统	D:\C#Project\BooK-Library-System-master\图书管理系统\ReturnBooks.Designer.cs	402	活动的
警告		未能找到引用的组件“Microsoft.VisualBasic.PowerPacks.Vs”。	图书管理系统			
警告		未能解析此引用。未能找到程序集“Microsoft.VisualBasic.PowerPacks.Vs, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL”。请检查磁盘上是否存在该程序集。 如果您的代码需要此引用，则可能出现编译错误。	图书管理系统			

能上传一下数据库脚本吗，文件导入失败

**Comment by ygsama** [comment]
数据库是sql server 2005 创建的，脚本不一定兼容。表不多，可以考率根据内容，手动建表。

**Comment by 2018149124** [comment]
我的和你的一样，请问最后你是怎么解决的呀

**Comment by ghost** [comment]
我是看着错误一点点改的，数据导入就好了。代码里面有点不兼容的问题；自己针对错误改就好了
